version: '3.9'
services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin
    restart: always
    links:
      - postgres:postgres
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    env_file: 
      - docker.env
    networks:
      - postgres
    
networks:
  postgres:
    driver: bridge


volumes:
  postgres_data:
  pgadmin_data:
